
cc_binary(
  name = 'zk_acl_admin_tool',
  srcs = 'zk_acl_admin_tool.cpp',
  deps = [
    '//common/zookeeper:zk_adaptor',
    '//thirdparty/gflags:gflags',
    '//thirdparty/glog:glog',
  ],
  
)

cc_binary(
  name = 'zk_node_admin_tool',
  srcs = 'zk_node_admin_tool.cpp',
  deps = [
    '//common/zookeeper:zk_adaptor',
    '//thirdparty/gflags:gflags',
    '//thirdparty/glog:glog',
  ],
  
)
