cc_test(
    name = 'condition_test',
    srcs = [
               'condition_test.cc'
           ],
    deps = [
               '//thirdparty/gtest:gtest',
               '//learning/proto:test_pb',
           ],
)

cc_test(
    name = 'lambda_parser_test',
    srcs = [
               'lambda_parser_test.cc'
           ],
    deps = [
               '//common/encoding:encoding',
               '//thirdparty/gtest:gtest',
               '//learning/proto:test_pb',
               '//learning/proto:condition_pb',
           ],
)