cc_library(
    name = 'mime',
    srcs = 'mime.cpp',
    deps = [
        '//common/base/string:string',
        '//thirdparty/glog:glog'
    ]
)

cc_test(
    name = 'mime_test',
    srcs = 'mime_test.cc',
    deps = ':mime'
)
