# Copyright (C), 1998-2012, Tencent
# Author: svdxu@tencent.com
# Date: 2013-03-13

cc_library(
  name = 'tea',
  srcs = [
    'tea.cc',
  ],
  deps = [
  ]
)

#cc_test(
#  name = 'decrypt_test',
#  srcs = [
#    'decrypt_test.cc'
#  ],
#  deps = [
#    ':tea'
#  ]
#)

cc_test(
  name = 'decrypt_test',
  srcs = [
    'decrypt_test.cc'
  ],
  deps = [
    ':tea'
  ]
)


