cc_library(
  name = 'curl_downloader',
  srcs = [
           'curl_downloader.cc',
         ],
  deps = [
           '//common/base/string:string',
           '//thirdparty/curl:curl',
           '//thirdparty/glog:glog',
         ],
)
