proto_library(
  name = 'test_pb',
  srcs = [
      'test.proto',
    ],
)
proto_library(
  name = 'tunner_config_pb',
  srcs = [
      'tunner_config.proto',
    ],
)
proto_library(
  name = 'evaluater_config_pb',
  srcs = [
      'evaluater_config.proto',
    ],
)
proto_library(
  name = 'condition_pb',
  srcs = [
      'condition.proto',
    ],
    deps = [
      '//common/proto:config_pb',
    ],
)