cc_library(
  name = 'hdfs_utility',
  srcs = 'hdfs_utility.cc',
  deps = '//common/base/string:string',
)

cc_test(
  name = 'hdfs_utiltiy_test',
  srcs = 'hdfs_utility_test.cc',
  deps = ':hdfs_utility',
)
