cc_test(
    name = 'evaluater_test',
    srcs = 'evaluater_test.cc',
    deps = [
        '//thirdparty/glog:glog',
        '//learning/evaluate/mine:mine',
        '//learning/proto:test_pb',
        '//learning/proto:evaluater_config_pb',
    ]
)
