cc_test(
  name = 'state_machine_test',
  srcs = [
           'state_machine_test.cc',
         ],
  deps = [
           '//common/config:config',
           '//thirdparty/glog:glog',
           '//thirdparty/gflags:gflags',
           '//thirdparty/gtest:gtest',
         ],
)