proto_library(
  name = 'crawler_config_pb',
  srcs = [
      'crawler_config.proto',
    ],
)

proto_library(
  name = 'feeder_config_pb',
  srcs = [
    'feeder_config.proto',
  ],
  deps = [
    '//common/proto:config_pb',
  ]
)

proto_library(
  name = 'product_pb',
  srcs = [
    'product.proto',
  ],
)