cc_library(
    name = 'utility',
    srcs = 'utility.cc',
    deps = [
        '//thirdparty/glog:glog',
        '//thirdparty/openssl:crypto',
        '//thirdparty/zlib:z',
    ]
)

cc_library(
    name = 'string',
    srcs = [
        'algorithm.cpp',
        'concat.cpp',
        'string_number.cpp',
        'string_piece.cpp',
    ],
    deps = [
        '//thirdparty/glog:glog',
    ]
)

