cc_test(
    name = 'tcp_client_socket_test',
    srcs = 'tcp_client_socket_test.cc',
    deps = [
        '//app/qzap/common/base:base',
        '//app/qzap/common/utility:utility',
        ':tcp_client_socket'
    ]

)

cc_library(
  name = 'tcp_client_socket',
  srcs = [
    'tcp_client_socket.cc',
  ],
)

